# Generated by Django 4.0.1 on 2022-01-20 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customers',
            fields=[
                ('CustomerId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerName', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetails',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('CustomerId', models.IntegerField()),
                ('ProductId', models.IntegerField()),
                ('OrderDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('ProductId', models.AutoField(primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=500)),
            ],
        ),
    ]
